// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: pkg/v1/pulsewatch/services.proto

package pulsewatch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPulseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPulseRequest) Reset() {
	*x = GetPulseRequest{}
	mi := &file_pkg_v1_pulsewatch_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPulseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPulseRequest) ProtoMessage() {}

func (x *GetPulseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_v1_pulsewatch_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPulseRequest.ProtoReflect.Descriptor instead.
func (*GetPulseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_v1_pulsewatch_services_proto_rawDescGZIP(), []int{0}
}

func (x *GetPulseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPulseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPulseResponse) Reset() {
	*x = GetPulseResponse{}
	mi := &file_pkg_v1_pulsewatch_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPulseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPulseResponse) ProtoMessage() {}

func (x *GetPulseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_v1_pulsewatch_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPulseResponse.ProtoReflect.Descriptor instead.
func (*GetPulseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_v1_pulsewatch_services_proto_rawDescGZIP(), []int{1}
}

func (x *GetPulseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_v1_pulsewatch_services_proto protoreflect.FileDescriptor

const file_pkg_v1_pulsewatch_services_proto_rawDesc = "" +
	"\n" +
	" pkg/v1/pulsewatch/services.proto\x12\n" +
	"pulsewatch\"%\n" +
	"\x0fGetPulseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10GetPulseResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2S\n" +
	"\n" +
	"PulseWatch\x12E\n" +
	"\bGetPulse\x12\x1b.pulsewatch.GetPulseRequest\x1a\x1c.pulsewatch.GetPulseResponseB1Z/github.com/ydkulks/PulseWatch/pkg/v1/pulsewatchb\x06proto3"

var (
	file_pkg_v1_pulsewatch_services_proto_rawDescOnce sync.Once
	file_pkg_v1_pulsewatch_services_proto_rawDescData []byte
)

func file_pkg_v1_pulsewatch_services_proto_rawDescGZIP() []byte {
	file_pkg_v1_pulsewatch_services_proto_rawDescOnce.Do(func() {
		file_pkg_v1_pulsewatch_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_v1_pulsewatch_services_proto_rawDesc), len(file_pkg_v1_pulsewatch_services_proto_rawDesc)))
	})
	return file_pkg_v1_pulsewatch_services_proto_rawDescData
}

var file_pkg_v1_pulsewatch_services_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_v1_pulsewatch_services_proto_goTypes = []any{
	(*GetPulseRequest)(nil),  // 0: pulsewatch.GetPulseRequest
	(*GetPulseResponse)(nil), // 1: pulsewatch.GetPulseResponse
}
var file_pkg_v1_pulsewatch_services_proto_depIdxs = []int32{
	0, // 0: pulsewatch.PulseWatch.GetPulse:input_type -> pulsewatch.GetPulseRequest
	1, // 1: pulsewatch.PulseWatch.GetPulse:output_type -> pulsewatch.GetPulseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_v1_pulsewatch_services_proto_init() }
func file_pkg_v1_pulsewatch_services_proto_init() {
	if File_pkg_v1_pulsewatch_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_v1_pulsewatch_services_proto_rawDesc), len(file_pkg_v1_pulsewatch_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_v1_pulsewatch_services_proto_goTypes,
		DependencyIndexes: file_pkg_v1_pulsewatch_services_proto_depIdxs,
		MessageInfos:      file_pkg_v1_pulsewatch_services_proto_msgTypes,
	}.Build()
	File_pkg_v1_pulsewatch_services_proto = out.File
	file_pkg_v1_pulsewatch_services_proto_goTypes = nil
	file_pkg_v1_pulsewatch_services_proto_depIdxs = nil
}
