// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: pulsewatch/pulsewatch.proto

package pulsewatch

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PulseWatch_GetPulse_FullMethodName          = "/pulsewatch.PulseWatch/GetPulse"
	PulseWatch_ServerStreamPulse_FullMethodName = "/pulsewatch.PulseWatch/ServerStreamPulse"
)

// PulseWatchClient is the client API for PulseWatch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PulseWatchClient interface {
	GetPulse(ctx context.Context, in *PulseRequest, opts ...grpc.CallOption) (*PulseResponse, error)
	ServerStreamPulse(ctx context.Context, in *PulseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PulseResponse], error)
}

type pulseWatchClient struct {
	cc grpc.ClientConnInterface
}

func NewPulseWatchClient(cc grpc.ClientConnInterface) PulseWatchClient {
	return &pulseWatchClient{cc}
}

func (c *pulseWatchClient) GetPulse(ctx context.Context, in *PulseRequest, opts ...grpc.CallOption) (*PulseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PulseResponse)
	err := c.cc.Invoke(ctx, PulseWatch_GetPulse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pulseWatchClient) ServerStreamPulse(ctx context.Context, in *PulseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PulseResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PulseWatch_ServiceDesc.Streams[0], PulseWatch_ServerStreamPulse_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PulseRequest, PulseResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PulseWatch_ServerStreamPulseClient = grpc.ServerStreamingClient[PulseResponse]

// PulseWatchServer is the server API for PulseWatch service.
// All implementations must embed UnimplementedPulseWatchServer
// for forward compatibility.
type PulseWatchServer interface {
	GetPulse(context.Context, *PulseRequest) (*PulseResponse, error)
	ServerStreamPulse(*PulseRequest, grpc.ServerStreamingServer[PulseResponse]) error
	mustEmbedUnimplementedPulseWatchServer()
}

// UnimplementedPulseWatchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPulseWatchServer struct{}

func (UnimplementedPulseWatchServer) GetPulse(context.Context, *PulseRequest) (*PulseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPulse not implemented")
}
func (UnimplementedPulseWatchServer) ServerStreamPulse(*PulseRequest, grpc.ServerStreamingServer[PulseResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamPulse not implemented")
}
func (UnimplementedPulseWatchServer) mustEmbedUnimplementedPulseWatchServer() {}
func (UnimplementedPulseWatchServer) testEmbeddedByValue()                    {}

// UnsafePulseWatchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PulseWatchServer will
// result in compilation errors.
type UnsafePulseWatchServer interface {
	mustEmbedUnimplementedPulseWatchServer()
}

func RegisterPulseWatchServer(s grpc.ServiceRegistrar, srv PulseWatchServer) {
	// If the following call pancis, it indicates UnimplementedPulseWatchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PulseWatch_ServiceDesc, srv)
}

func _PulseWatch_GetPulse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PulseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PulseWatchServer).GetPulse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PulseWatch_GetPulse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PulseWatchServer).GetPulse(ctx, req.(*PulseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PulseWatch_ServerStreamPulse_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PulseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PulseWatchServer).ServerStreamPulse(m, &grpc.GenericServerStream[PulseRequest, PulseResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PulseWatch_ServerStreamPulseServer = grpc.ServerStreamingServer[PulseResponse]

// PulseWatch_ServiceDesc is the grpc.ServiceDesc for PulseWatch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PulseWatch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pulsewatch.PulseWatch",
	HandlerType: (*PulseWatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPulse",
			Handler:    _PulseWatch_GetPulse_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStreamPulse",
			Handler:       _PulseWatch_ServerStreamPulse_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pulsewatch/pulsewatch.proto",
}
