// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: pulsewatch/pulsewatch.proto

package pulsewatch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PulseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PulseRequest) Reset() {
	*x = PulseRequest{}
	mi := &file_pulsewatch_pulsewatch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PulseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulseRequest) ProtoMessage() {}

func (x *PulseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulsewatch_pulsewatch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulseRequest.ProtoReflect.Descriptor instead.
func (*PulseRequest) Descriptor() ([]byte, []int) {
	return file_pulsewatch_pulsewatch_proto_rawDescGZIP(), []int{0}
}

func (x *PulseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PulseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PulseResponse) Reset() {
	*x = PulseResponse{}
	mi := &file_pulsewatch_pulsewatch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PulseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulseResponse) ProtoMessage() {}

func (x *PulseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pulsewatch_pulsewatch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulseResponse.ProtoReflect.Descriptor instead.
func (*PulseResponse) Descriptor() ([]byte, []int) {
	return file_pulsewatch_pulsewatch_proto_rawDescGZIP(), []int{1}
}

func (x *PulseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pulsewatch_pulsewatch_proto protoreflect.FileDescriptor

const file_pulsewatch_pulsewatch_proto_rawDesc = "" +
	"\n" +
	"\x1bpulsewatch/pulsewatch.proto\x12\n" +
	"pulsewatch\"\"\n" +
	"\fPulseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\rPulseResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x99\x01\n" +
	"\n" +
	"PulseWatch\x12?\n" +
	"\bGetPulse\x12\x18.pulsewatch.PulseRequest\x1a\x19.pulsewatch.PulseResponse\x12J\n" +
	"\x11ServerStreamPulse\x12\x18.pulsewatch.PulseRequest\x1a\x19.pulsewatch.PulseResponse0\x01B*Z(github.com/ydkulks/PulseWatch/pulsewatchb\x06proto3"

var (
	file_pulsewatch_pulsewatch_proto_rawDescOnce sync.Once
	file_pulsewatch_pulsewatch_proto_rawDescData []byte
)

func file_pulsewatch_pulsewatch_proto_rawDescGZIP() []byte {
	file_pulsewatch_pulsewatch_proto_rawDescOnce.Do(func() {
		file_pulsewatch_pulsewatch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pulsewatch_pulsewatch_proto_rawDesc), len(file_pulsewatch_pulsewatch_proto_rawDesc)))
	})
	return file_pulsewatch_pulsewatch_proto_rawDescData
}

var file_pulsewatch_pulsewatch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pulsewatch_pulsewatch_proto_goTypes = []any{
	(*PulseRequest)(nil),  // 0: pulsewatch.PulseRequest
	(*PulseResponse)(nil), // 1: pulsewatch.PulseResponse
}
var file_pulsewatch_pulsewatch_proto_depIdxs = []int32{
	0, // 0: pulsewatch.PulseWatch.GetPulse:input_type -> pulsewatch.PulseRequest
	0, // 1: pulsewatch.PulseWatch.ServerStreamPulse:input_type -> pulsewatch.PulseRequest
	1, // 2: pulsewatch.PulseWatch.GetPulse:output_type -> pulsewatch.PulseResponse
	1, // 3: pulsewatch.PulseWatch.ServerStreamPulse:output_type -> pulsewatch.PulseResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pulsewatch_pulsewatch_proto_init() }
func file_pulsewatch_pulsewatch_proto_init() {
	if File_pulsewatch_pulsewatch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pulsewatch_pulsewatch_proto_rawDesc), len(file_pulsewatch_pulsewatch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pulsewatch_pulsewatch_proto_goTypes,
		DependencyIndexes: file_pulsewatch_pulsewatch_proto_depIdxs,
		MessageInfos:      file_pulsewatch_pulsewatch_proto_msgTypes,
	}.Build()
	File_pulsewatch_pulsewatch_proto = out.File
	file_pulsewatch_pulsewatch_proto_goTypes = nil
	file_pulsewatch_pulsewatch_proto_depIdxs = nil
}
